tree(	||T||,
	tree(	EW,
	     	tree(pos,word,POS)),
	tree(STOP,tree(word)),
	tree(EW,tree(pos,word,POS)),
	AND,
	tree(EW,tree(pos,word,POS)),
	tree(EW,tree(pos,word,POS)),
	tree(EW,tree(pos,word,POS)),
	tree(STOP,tree(word)),
	tree(EW,tree(pos,word,POS)),
	tree(EW,tree(pos,word,POS)),
	tree(EW,tree(pos,word,POS)),
	EXC)
